### PR TITLE
Create log event parser and event handlers

### PR DESCRIPTION
**Pull request by sommern**
The log event parser is complete. Only two event handlers have been
created so far: one for student submissions and one for faculty uploads.

These handlers are still stubs. They extract the necessary information
from the log but they do not yet perform the actions they will need to
perform.

### CODE REVIEW

**Comment by sommern** [comment]
I started log events documentation in the wiki:
https://github.com/git-keeper/git-keeper/wiki/Log-events

**Comment by bjcoleman** [comment]
We've done other documentation in `docs/`.  We should be consistent.

**Comment by bjcoleman** [comment]
We can discuss the documentation piece, and if we decide to put it in `docs` that can be a new pull request.  Merging.

**Comment by sommern** [comment]
The documentation should certainly end up in docs eventually. But right now it's documentation about stuff that isn't fully implemented or even fully thought through. The wiki feels like a good place to start documentation about moving targets. Putting it in a pull request is nice because of comments, but putting it in the wiki is nice because you don't have to futz around with git and branches, and we can both edit it anytime.

**Pull request merged**
