### PR TITLE
"Add Student Twice" test added to gkeep_modify

### PR DESCRIPTION
**Pull request by ZacharyB19**
This test demonstrates the same student being able to be added twice.

### CODE REVIEW

**Comment by sommern** [comment]
There is an inconsistency here since the test is marked as `error` yet it expects the `gkeep modify` to succeed. A decision needs to be made as to whether we want duplicate students to be silently ignored, or if the modify should fail. I am inclined to think it should fail, since otherwise the faculty may think they have a valid class roster in the CSV file when really there is at least one extra entry.

**Comment by bjcoleman** [comment]
Also, I think the test can be simplified.  `kermit` and `gonzo` are added when the class is created.  It would be better to modify the course to re-add `kermit` (for example).

**Comment by bjcoleman** [comment]
I agree that adding a duplicate student should be an error.  @sommern Do you have a sense of how hard it would be to change the code?  If fairly easy, then we can have Zach do it.

**Comment by sommern** [comment]
@bjcoleman @ZacharyB19 This should be relatively easy to implement. If a duplicate student is encountered when building the list of students in `students_from_csv()` you can raise a `StudentError` exception with a helpful error message (like `<student email> appears more than once`). This exception will be caught at the appropriate place and the add or modify will fail gracefully.

**Comment by ZacharyB19** [comment]
After my last commit "fd03e5d", the "Add Student Twice" test should be complete. In order to fix the issue preventing from this test from passing, I had to change the type of exception that was being raised. Instead of a StudentError, a GkeepRobotException needed to be raised. Also in order to properly compare the students being added into the class, I needed to only compare their email_address attribute instead of the whole student itself.

**Comment by bjcoleman** [comment]
The changes you made are good, and I am happy to accept the changes.

You still need to work on your messages.  On this page I can see the commit hashes and the messages.  In addition, I can (and will) look at the modified files to see *how* you made changes.  In these messages you simply need to tell us *what* you are changing.  For example, here is an appropriate commit message for this work:

* Implements a test that ensures that it is an error to add a duplicate student to a class using `gkeep modify`.
* Adds functionality to made the above case an error (this case was ignored previously).
* Corrects a bug in the `gkeep_modify_fails` method that caused the method to succeed always.

**Pull request merged**
